server:
  port: 9090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: ${demo.database.username}
    password: ${demo.database.password}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  config:
    import: vault://
  cloud:
    vault:
      enabled: true
      authentication: TOKEN
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        backend: secret
        default-context: spring-demo
        profile-separator: /
      uri: http://localhost:8200

logging:
  level:
    org:
      springframework:
        vault:
          core:
            env: DEBUG



